# **Linear Algebra (Basics+python Impelmentations)**

Linear algebra is the branch of mathematics concerning linear equations and linear functions and their representations through matrices and vector spaces.

Machine Learning relies heavily on Linear Algebra, so it is essential to understand what vectors and matrices are, what operations you can perform with them, and how they can be useful.

If you have had no exposure at all to linear algebra or practical implementation, this class would be helpful to you

If you are already familiar with linear algebra, feel free to skip this class 


<div>
<img src="https://drive.google.com/uc?export=view&id=1m478MlparnngiauNlmH--DEkqNjsYRgu" width="500"/>
</div>

<div>
<img src="https://drive.google.com/uc?export=view&id=1Qw8qBhC2bUvSheR05TzcUBz1NMMwxhID" width="800"/>
</div>

# 1. Import functions

In [ ]:
# All necessary import functions
import numpy as np
from numpy.linalg import eig
from scipy.stats import norm

# 2. Scalars, Vectors, Matrices and Tensors

__Scalars:__ are just a single number. For example temperature, which is denoted by just one number.


__Vectors:__ are an array of numbers. The numbers are arranged in order and we can identify each individual number by its index in that ordering. We can think of vectors as identifying points in space, with each element giving the coordinate along a different axis. In simple terms, a vector is an arrow representing a quantity that has both magnitude and direction wherein the length of the arrow represents the magnitude and the orientation tells you the direction. For example wind, which has a direction and magnitude.

__Matrices:__ A matrix is a 2D-array of numbers, so each element is identified by two indices instead of just one. If a real valued matrix $A$ has a height of *m* and a width of *n*, then we say that $A \in \mathbb{R}^{m \times n}$. We identify the elements of the matrix as $A_{m,n}$ where *m* represents the row and *n* represents the column.


<div>
<img src="https://drive.google.com/uc?export=view&id=1VO-cfU6rStdv0ExEKqrDqUlKZAGQ5bIZ" width="500"/>
</div>

__Tensor:__

<div>
<img src="https://drive.google.com/uc?export=view&id=1BY-AdeqOG8EOqlmA-LaxnMErYcGlM8Ms" width="500"/>
</div>








In other words:

- Order 0 Tensor is a Scalar
- Order 1 Tensor is a Vector
- Order 2 Tensor is a Matrix
- Order 3 Tensor is a 3-Tensor
- Order n Tensor is a n-Tensor

# 3. Defining vectors

<div>
<img src="https://drive.google.com/uc?export=view&id=1F8ehl1K-mYFrQweQ813mFfdXkgPpaFqy" width="800"/>
</div>



In [ ]:
#Defining a Row-Vector
row_vec=np.array([[5,7,9]])
print(row_vec)
print('The shape of the vector' , row_vec.shape)

[[5 7 9]]
The shape of the vector (1, 3)


In [ ]:
#Defining a Column-Vector
column_vec=np.array([[5,7,9]]).T
print(column_vec)
print('The shape of the vector' , column_vec.shape)

[[5]
 [7]
 [9]]
The shape of the vector (3, 1)


# 4. About Matrix

Images, Tables, Text data will be converted into Matrix for further manipulation and processing

<div>
<img src="https://drive.google.com/uc?export=view&id=1m2m82CoVxnkVoZpKMMQ_ygDLKLkgK8_s" width="500"/>
</div>

## 4a. Matrix Operations

In [ ]:
# Defining a matrix
matrix_A = np.array([[1, 1, 1],
               [1,1, 1],
               [1, 1, 1]])
print(matrix_A)
print('The shape of the matrix A is',matrix_A.shape)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
The shape of the matrix A is (3, 3)


In [ ]:
# Defining a matrix
matrix_B = np.array([[2, 4, 6],
               [2, 4, 6],
               [2, 4, 6]])
print('The shape of the matrix B is',matrix_B.shape)

The shape of the matrix B is (3, 3)


In [ ]:
# Scalar * Matrix-multiplication

10 * matrix_A

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

We can add matrices to each other as long as they have the same shape, just by adding their corresponding elements:

$$\color{orange}{C = A + B \ where \ C_{i,j} = A_{i,j} + B_{i,j} \tag{1}}$$

In [ ]:
#Matrix addition
matrix_A + matrix_B

array([[3, 5, 7],
       [3, 5, 7],
       [3, 5, 7]])

To compute the dot product between $A$ and $B$ we compute $C_{i, j}$ as the dot product between row *i* of $A$ and column *j* of $B$.

![Dot Product](https://raw.githubusercontent.com/adhiraiyan/DeepLearningWithTF2.0/master/notebooks/figures/fig0202b.jpg)

In [ ]:
#Matrix Mutliplication
np.dot(matrix_A, matrix_B)

array([[ 6, 12, 18],
       [ 6, 12, 18],
       [ 6, 12, 18]])

In [ ]:
#Transpose-Define not a square matrix
matrix_A = np.array([[1, 1, 1,1],
               [2,2,2,2],
               [3,3,3,3]])
transp=matrix_A.T
print('Before Transpose')
print(matrix_A.shape)
print(matrix_A,'\n')
print('After Transpose')
print(transp)
print(transp.shape)

Before Transpose
(3, 4)
[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]] 

After Transpose
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
(4, 3)


To define the matrix product of matrices $A \ \text{and} \ B, \ A$ must have the same number of columns as $B$. If $A$ is of shape *m x n* and $B$ is of shape *n x p*, then $C$ is of shape *m x p*.

$$\color{orange}{C_{i, j} = \displaystyle\sum_k A_{i, k} B_{k, j} \tag{3}}$$

If you do not recall how matrix multiplication is performed, take a look at:

![Multiplying Matrices](https://raw.githubusercontent.com/adhiraiyan/DeepLearningWithTF2.0/master/notebooks/figures/fig0202a.jpg)

In [ ]:
#Matrix-Vector multiplication
#do a vector mul
#(4,3) (3,1) --> (4,1)
matrix_A= np.array([[ 5, 1 ,3], 
                  [ 1, 1 ,1], 
                  [ 1, 2 ,1],
                   [ 1, 2 ,1]
                    ])
vector_b = np.array([[2],
              [2],
              [2]])
result=matrix_A.dot(vector_b)
print(matrix_A.shape,vector_b.shape)

print(result)
print('Shape of the result',result.shape)


(4, 3) (3, 1)
[[18]
 [ 6]
 [ 8]
 [ 8]]
Shape of the result (4, 1)


In [ ]:
# not a perfect case for multiplication
#Matrix-Matrix multiplication

matrix_A= np.array([[ 5, 1 ], 
                  [ 1, 1 ], 
                  [ 1, 2 ]])
vector_b = np.array([[1, 2],
              [1, 2],
              [1, 2]])
print(matrix_A.shape,vector_b.shape)

try:
  result_case2=matrix_A.dot(vector_b)
  print(result_case2)
  print('Shape of the result',result_case2.shape)
except:
  print('The shapes are inappropriate for multiplication')




(3, 2) (3, 2)
The shapes is inappropriate for multiplication


## 4b. Solving Equations Using Matrix

If you try different values for Matrix A, you will see that, not all $A$ has an inverse and we will discuss the conditions for the existence of $A^{-1}$ in the following section.

We can then solve the equation $Ax = b$ as:

$$
\color{Orange}{A^{-1} Ax = A^{-1} b} \\
\color{Orange}{I_n x = A^{-1} b} \\
\color{Orange}{x  =A^{-1} b \tag{10}}
$$
where I is the Identity Matrix


In [ ]:
# Solving an equation- 2 unknown
# 2x + 3y =8 --> equ 1
# 3x + 2y =7 --> equ 2

mat_A = np.array([[2, 3],
               [3, 2]])
vec_b = np.array([[8],[7]])

In [ ]:
#FInding A-Inverse
A_inverse = np.linalg.inv(mat_A)
print(A_inverse)

[[-0.4  0.6]
 [ 0.6 -0.4]]


In [ ]:
# unknown values
x= np.dot( A_inverse,vec_b) 
print(x)

[[1.]
 [2.]]


In [ ]:
# Verification
np.dot( mat_A,x)

array([[8.],
       [7.]])

In [ ]:
# Solving an equation- 3 unknown
mat_A = np.array([[4, -2, 3],
               [1, 3, -4],
               [3, 1, 2]])
vec_b = np.array([[1], [-7], [5]])


In [ ]:
x = np.linalg.solve(mat_A, vec_b)
x

array([[-1.],
       [ 2.],
       [ 3.]])

In [ ]:
# Verification
np.dot(mat_A , x )# use np.dot

array([[ 1.],
       [-7.],
       [ 5.]])

## Limitations of finding $A^{-1}$

• For $A ∈ R^{n×n}$ , |A| = 0 if and only if A is singular (i.e., non-invertible). (If A is singular
then it does not have full rank, and hence its columns are linearly dependent. 

•  Not all matrices is invertible sometimes we cannot, we cannot find the $A^{-1}$

• The computatinal complexity of finding $A^{-1}$ is $O(n^3)$ . ie, as the dataset size grows it expensive.


# 5. Norms

In machine learning if we need to measure the magnitude of vectors, we use a function called a __norm__. And norm is what is generally used to evaluate the error of a model. Formally, the $L^P$ norm is given by:

$$\color{Orange}{||x||_p = \big(\displaystyle\sum_i |x_i|^p\big)^{1/p} \tag{12}}$$

for $p \in \mathbb{R}, p \geq 1$

The $L^2$ norm with *p=2* is known as the __Euclidean norm__. Which is simply the Euclidean distance from the origin to the point identified by $x$. It is also common to measure the size of a vector using the squared $L^2$ norm, which can be calculated simply as $x^{\top}x$

In [ ]:
vec_a=np.array([4,3]) #rename the variable

In [ ]:
#Norm L1-Norm
from numpy import linalg as LA
norm1=LA.norm(vec_a ,1)
print('L1-norm',norm1)

L1-norm 7.0


In [ ]:
#Finding L2-Norm
norm2=LA.norm(vec_a)
print('L2-norm',norm2)

L2-norm 5.0


## Norms on Matrix


If we wish to measure the magnitude of a matrix, in context of deep learning, the most common way to do this is with the __Frobenius norm__:

$$\color{Orange}{\parallel A \parallel_F = \sqrt{\displaystyle\sum_{i, j} A^2_{i, j}} \tag{16}}$$

which is analogous to the $L^{2}$ norm of a vector.

Meaning for example for a matrix:

$$
A =
\begin{pmatrix}
2 & -1 & 5 \\
0 & 2 & 1 \\
3  & 1 & 1  \\
\end{pmatrix}
$$
 
$||A|| = [2^2 + (-1^2) + 5^2 + 0^2 + 2^2 + 1^2 + 3^2 + 1^2 + 1^2]^{1/2}$
$ = [46]^{1/2}$


In [ ]:
# Forbenius norm -L2 norm of a matrix
matrix_A = np.array([[2,-1,5],[0,2,1],[3,1,1]])
frob=LA.norm(matrix_A,'fro')
print(frob)

6.782329983125268


# 6. The Trace Operator


The trace operator gives the sum of all the diagonal entries of a matrix:

$$\color{Orange}{Tr(A) = \displaystyle\sum_i A_{i,i} \tag{27}}$$


In [ ]:
# Defining the matrix
matrix_A = np.array([[1,1,1],[0,1,2],[1,5,3]])
print(matrix_A) 

# To find the trace of the matrix
trace=matrix_A.trace()
print('The trace of the matrix is',trace)

[[1 1 1]
 [0 1 2]
 [1 5 3]]
The trace of the matrix is 5


# 7. Eigenvalues and Eigenvectors

<div>
<img src="https://drive.google.com/uc?export=view&id=1VcBBU6x7_H5n_yfZsPIUnalHVwHo7Ry6" width="700"/>
</div>


In [ ]:

# Percentage of marks and no. of hours studied
#
students = np.array([[85.4, 5],
            [82.3, 6],
            [97, 7],
            [96.5, 6.5]])

#Covariance matrix  (it is symmetric) encodes the correlations between variables of a vector.

cov_matrix = np.cov(students.T)
#
# Calculate Eigenvalues and Eigenmatrix
#
eigenvalues, eigenvectors = eig(cov_matrix)

In [ ]:
print('Eigen values \n' , eigenvalues)
print('Eigen vectors \n' , eigenvectors)

Eigen values 
 [57.5359938  0.3065062]
Eigen vectors 
 [[ 0.99630048 -0.08593813]
 [ 0.08593813  0.99630048]]


Lets verify , $Av=\lambda v$

In [ ]:
# Left hand side
cov_matrix.dot(eigenvectors[:, 0])

array([57.323138  ,  4.94453555])

In [ ]:
# Right hand side
eigenvalues[0]*eigenvectors[:, 0]

array([57.323138  ,  4.94453555])

For more idea on Eigenvalues and vectors --> https://www.youtube.com/watch?v=PFDu9oVAE-g&ab_channel=3Blue1Brown

Real time applications in Machine Learning include **dimensionality Reduction (Principal Component Analysis)**




**To Learn more about linear Algebra**


1.   For a quick-brief reference, please refer to CS229 Standford materials (http://cs229.stanford.edu/section/cs229-linalg.pdf)
2.   For a detailed course and in-depth understanding, we highly recommend this course
Prof. Gilbert Strang’s on linear algebra( https://ocw.mit.edu/courses/mathematics/18-06-linear-algebra-spring-2010/video-lectures/)




# 💫 Congratulations

You have successfully completed Brushup on Linear Algebra and learnt it through python implementations
